### ISSUE TITLE
Github模拟登陆报错

### ISSUE THREAD

**Issue by CaptainTec** [Kr1s77/awesome-python-login-model#1]
老铁，Github那个模拟登陆显示下标越界啊。
File "/Users/fuli/vim_practice/github_bew.py", line 46, in post_param
    'authenticity_token': self.get_param()[0],
IndexError: list index out of range

我重新解析了 authenticity_token，然后又是HTTP 422错误。。。

**Comment by CriseLYJ** [comment]
Github代码已重构，请重新试一下

**Comment by CaptainTec** [comment]
response 返回码 还是422呀 大兄弟@_@
![image](https://user-images.githubusercontent.com/26764515/53927539-2c258400-40c2-11e9-8d49-9d96c473c834.png)
觉得的是csrf没验证通过的问题。
也就是cookie的问题 /捂脸
