### ISSUE TITLE
知乎登录报错

### ISSUE THREAD

**Issue by A-BenMao** [Kr1s77/awesome-python-login-model#10]
execjs._exceptions.ProgramError: TypeError: 'exports' 未定义
 定位不出来是哪错了

**Comment by QUXINYIN** [comment]
我是Python3.6

**Comment by CriseLYJ** [comment]
你确定js文件和py文件是在同一个目录下？？我的环境下知乎登录是没有问题的

**Comment by evaniswong** [comment]
我也是报TypeError: 'exports' 未定义， js文件和py文件确定是在同一个目录下，麻烦指导。

**Comment by CriseLYJ** [comment]
注意需要先安装 PyExecJS 库。 查看一下有没有安装

**Comment by CriseLYJ** [comment]
## 也有可能是你的node环境有问题
- 由于是你本地的JScript引擎只有一个默认的JScript，所以会造成json未定义的错误。
- execjs会自动使用当前电脑上的运行时环境
- 解决办法：安装一个nodejs的V8引擎就可以了

**Comment by CriseLYJ** [comment]
如果安装之后，可以使用，记得给我个回应

**Comment by midpushgogo** [comment]
同样的问题  装了nodejs就能用了 谢谢~

**Comment by CriseLYJ** [comment]
好的  为你们感到高兴。欢迎向我提pr

**Comment by PalaChen** [comment]
> 同样的问题 装了nodejs就能用了 谢谢~

我装了nodejs还是报错，我的python3.5.2

**Comment by CriseLYJ** [comment]
看一下引擎版本

**Comment by PalaChen** [comment]
同样的问题 装了nodejs 然后重启电脑可以使用

**Comment by CriseLYJ** [comment]
能用就好

**Comment by FangbaiZhang** [comment]
@CriseLYJ  你好！我在输入电话号码后，按了ENTER，但是程序没有反应，没有出现输入密码的部分，这是什么问题呢？

**Comment by CriseLYJ** [comment]
密码为隐藏，输完账号会车直接输密码

**Comment by FangbaiZhang** [comment]
关键我这里输入电话号码，回车之后，输入密码，密码没有隐藏是明文显示的

**Comment by CriseLYJ** [comment]
你试试直接输入密码，不行的话就把代码改一下，密码哪里改成input

**Comment by FangbaiZhang** [comment]
我直接将self,username 和self.password的值直接填写我的账号和密码，可以运行出来填写验证码了，已经可以报了上面回复中的execjs._exceptions.ProgramError: TypeError: 'exports' 未定义错误了  我去安装nodejs的V8引擎

**Comment by dingjianhub** [comment]
您好，我是在Windows上跑的程序，我电脑本机安装了Nodejs，安装了一个软件叫 ANACONDA ,在里面运行python程序，也在这个软件的环境内安装了nodejs 。但是死活就是跑不起来，提示如下：
Traceback (most recent call last):
  File "zhihu.py", line 19, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'

**Comment by dingjianhub** [comment]
您好，我这边输入手机号完成后，回车准备输入密码，报错了……不知如何修改呢？难道官方已经修改了登录？
Traceback (most recent call last):
  File "zhihu.py", line 206, in <module>
    account.login(captcha_lang='en', load_cookies=True)
  File "zhihu.py", line 66, in login
    self._check_user_pass()
  File "zhihu.py", line 195, in _check_user_pass
    self.password = input.getpass("password:")
AttributeError: 'builtin_function_or_method' object has no attribute 'getpass'

**Comment by dingjianhub** [comment]
> execjs._exceptions.ProgramError: TypeError: 'exports' 未定义
> 定位不出来是哪错了
请问是哪个平台，什么环境？

**Comment by fengjunling** [comment]
{'error': {'message': 'ZERR_NO_AUTH_TOKEN', 'code': 100}} 验证码返回这个错误是怎么回事呀
![image](https://user-images.githubusercontent.com/26746391/55090386-fb95a080-50e9-11e9-8fc1-7e149a8b03f5.png)

**Comment by hesunan** [comment]
f:\anaconda\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)

ProgramError: TypeError: 'exports' 未定义
我想问一下，这个问题出在哪

**Comment by benzmjs** [comment]
> ## 也有可能是你的node环境有问题
> * 由于是你本地的JScript引擎只有一个默认的JScript，所以会造成json未定义的错误。
> * execjs会自动使用当前电脑上的运行时环境
> * 解决办法：安装一个nodejs的V8引擎就可以了

如何安装nodeks的v8引擎呢？
