### ISSUE TITLE
网易云下载报错

### ISSUE THREAD

**Issue by myrensheng** [Kr1s77/awesome-python-login-model#100]
![image](https://user-images.githubusercontent.com/39438763/72057485-73475b80-3309-11ea-8a5f-d6c23f31917d.png)

**Comment by CharlesPikachu** [comment]
可以试试这里的例子：https://github.com/CharlesPikachu/DecryptLogin

**Comment by Kr1s77** [comment]
可能是由于 pycrypto‎ 已经多年没有维护 pycrypto‎ 切换为pycrypto‎demo |  https://github.com/dlitz/pycrypto/issues/238，代码已经更新

卸载原有的 pycrypto‎ ``pip uninstall crypto pycryptodome``
安装 pycryptodome 即可 ``pip install pycrypto‎demo ``。

**Comment by Kr1s77** [comment]
@myrensheng 
可能是由于 pycrypto‎ 已经多年没有维护 pycrypto‎ 切换为pycrypto‎demo | https://github.com/dlitz/pycrypto/issues/238，代码已经更新

卸载原有的 pycrypto‎ ``pip uninstall crypto pycryptodome``
安装 pycryptodome 即可 ``pip install pycrypto‎demo`` 。
测试环境 ``Windows 10``
