### ISSUE TITLE
Hi，guys~推一波自己的模拟登录库

### ISSUE THREAD

**Issue by CharlesPikachu** [Kr1s77/awesome-python-login-model#101]
项目地址：
[https://github.com/CharlesPikachu/DecryptLogin](https://github.com/CharlesPikachu/DecryptLogin)
利用requests模拟登录各大网站，目前已经完成：

- 新浪微博
- 知乎
- B站
- 中国铁路12306
- 豆瓣
- Github
- 网易云音乐
- 今日头条
- QQ空间等腾讯系网站

里面还有很多有趣的小例子，欢迎关注~

**Comment by dragon8github** [comment]
建议修改一下 href
