### ISSUE TITLE
能加一个虾米让我学习一下吗？

### ISSUE THREAD

**Issue by jasonyun** [Kr1s77/awesome-python-login-model#102]
如题，能加一个虾米让我学习一下吗？

**Comment by Kr1s77** [comment]
> 
> 
> 如题，能加一个虾米让我学习一下吗？

@jasonyun 👌

**Comment by Kr1s77** [comment]
@jasonyun 虾米已经添加 https://github.com/Kr1s77/awesome-python-login-model/tree/master/xiamiMusic
