### ISSUE TITLE
chrome.exe怎么修改源码？

### ISSUE THREAD

**Issue by ryan147k** [Kr1s77/awesome-python-login-model#108]
chrome.exe 在windows下打开是乱码，怎么转换成源码进行修改呢？

**Comment by Kr1s77** [comment]
@ryan147k 就是乱码的，你可以参考我公众号的文章   https://mp.weixin.qq.com/s/GLYvkZj2G8NKU75uBdzgKg

**Comment by thouger** [comment]
chromium官网就有教你怎么编译chromium

**Comment by ryan147k** [comment]
solved
