### ISSUE TITLE
套有Cloudflare CDN的小网站怎么登陆

### ISSUE THREAD

**Issue by fbigun** [Kr1s77/awesome-python-login-model#110]

**Comment by Kr1s77** [comment]
发送可以联系我邮箱: criselyj@163.com 发送样本链接。

**Comment by Kr1s77** [comment]
@fbigun 了解了一下 Cloudflare CDN 的网站，它只是限制某些地区的IP访问等操作, 应该不会影响到模拟登录的问题，加载时你可以尝试让程序等待，我这里没有样本，只是大概猜测一下，估计就是这个样子了，这种方案并不是应对模拟登录。
