### ISSUE TITLE
知乎的登录怎么没了

### ISSUE THREAD

**Issue by cuipu** [Kr1s77/awesome-python-login-model#111]
作者您好，我想问一下知乎的登录怎么没了？

**Comment by CharlesPikachu** [comment]
maybe you could use this: https://github.com/CharlesPikachu/DecryptLogin

**Comment by cuipu** [comment]
Thank you ver much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kr1s77/awesome-python-login-model"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 上午10:07
收件人:&nbsp;"Kr1s77/awesome-python-login-model"<awesome-python-login-model@noreply.github.com&gt;;
抄送:&nbsp;"崔璞"<250097795@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kr1s77/awesome-python-login-model] 知乎的登录怎么没了 (#111)





 
maybe you could use this: https://github.com/CharlesPikachu/DecryptLogin

**Comment by Kr1s77** [comment]
@CharlesPikachu 加油
