### ISSUE TITLE
关于登录原理

### ISSUE THREAD

**Issue by houkensjtu** [Kr1s77/awesome-python-login-model#14]
如果有时间的话，是否可以用文档的形式分享一下是如何反向工程然后寻找到登录方法的？
或者，如果其他人看到你的代码，是否可以PR自己分析的原理文章？
谢谢！

**Comment by CriseLYJ** [comment]
可以，欢迎哈哈哈

**Comment by CriseLYJ** [comment]
我需要更的人过来帮助我，众志成城不是吗？？
