### ISSUE TITLE
我想知道怎么模拟12306买票。。

### ISSUE THREAD

**Issue by lvshp** [Kr1s77/awesome-python-login-model#17]

**Comment by CriseLYJ** [comment]
12306验证码验证准确率可能不是很高，一般自动买票，都是用打码平台，目前市面上大部分打卡平台都是人工打码吧！

**Comment by lvshp** [comment]
好的，感谢回复

**Comment by CriseLYJ** [comment]
不用客气，还是要感谢你们给我提Issues

**Comment by bugTacit** [comment]
我个人觉得12306可以模拟手机端User-Agent，手机app买票是不需要验证码的，应该可以绕开验证
