### ISSUE TITLE
dropbox注册

### ISSUE THREAD

**Issue by bay1ts** [Kr1s77/awesome-python-login-model#3]
各种方式均会出现谷歌验证码，但是自己打开浏览器就没问题。不知道怎么造成的。

**Comment by CriseLYJ** [comment]
好的，我会尝试来解决它💗

**Comment by bay1ts** [comment]
十分感谢你的工作。这个问题困扰我一段时间，主要是 谷歌验证码触发策略琢磨不到。如果您有时间可以尝试一下。谢谢
