### ISSUE TITLE
最近在搞天涯论坛模拟登录，发现一直登录不了，求增加该项目

### ISSUE THREAD

**Issue by fengyelingdu** [Kr1s77/awesome-python-login-model#51]
最近在搞天涯论坛模拟登录，发现一直登录不了，求增加该项目

**Comment by CriseLYJ** [comment]
- 为什么我注册天涯论坛，他们打电话的系统给我打过来就响了一下，根本接不到，我能借个账号吗？？
- 这个网站被爬怕了吧，注册的验证码，我都看不懂哈哈

**Comment by CriseLYJ** [comment]
@fengyelingdu 
> 爬取天涯的时候需要多账号吗，如果不需要可以使用第三方登陆，比如微博登陆，可以直接跳过验证的吧

**Comment by fengyelingdu** [comment]
> @fengyelingdu
> 
> > 爬取天涯的时候需要多账号吗，如果不需要可以使用第三方登陆，比如微博登陆，可以直接跳过验证的吧

就是想模拟登录，不过就是登录不了，验证码倒是可以用人工打码

**Comment by fengyelingdu** [comment]
> * 为什么我注册天涯论坛，他们打电话的系统给我打过来就响了一下，根本接不到，我能借个账号吗？？
> * 这个网站被爬怕了吧，注册的验证码，我都看不懂哈哈

账号密码我发你邮箱了，感谢

**Comment by peimin1** [comment]
from selenium import webdriver


def get_cookies(username, password):

    driver = webdriver.Chrome()

    driver.get("http://www.tianya.cn/")

    driver.find_element_by_xpath('//a[@class="normal-login-tab"]').click()  # 切换登录方式

    driver.find_element_by_xpath('//input[@id="vwriter"]').send_keys(username)  # 输入用户
    driver.find_element_by_xpath('//input[@type="password"]').send_keys(password)  # 输入密码
    driver.find_element_by_xpath("//button[@class='loginWin-submit-btn']").click()  # 点击登录

    # todo 需要在这里判断是否登录成功
    print(driver.page_source)
    driver.close()


if __name__ == '__main__':
    # 在这里输入用户名，密码
    get_cookies(username="", password="")

**Comment by fengyelingdu** [comment]
> from selenium import webdriver
> 
> def get_cookies(username, password):
> 
> ```
> driver = webdriver.Chrome()
> 
> driver.get("http://www.tianya.cn/")
> 
> driver.find_element_by_xpath('//a[@class="normal-login-tab"]').click()  # 切换登录方式
> 
> driver.find_element_by_xpath('//input[@id="vwriter"]').send_keys(username)  # 输入用户
> driver.find_element_by_xpath('//input[@type="password"]').send_keys(password)  # 输入密码
> driver.find_element_by_xpath("//button[@class='loginWin-submit-btn']").click()  # 点击登录
> 
> # todo 需要在这里判断是否登录成功
> print(driver.page_source)
> driver.close()
> ```
> if **name** == '**main**':
> # 在这里输入用户名，密码
> get_cookies(username="", password="")

感谢，想用http请求去模拟登录

**Comment by peimin1** [comment]
> > from selenium import webdriver
> > def get_cookies(username, password):
> > ```
> > driver = webdriver.Chrome()
> > 
> > driver.get("http://www.tianya.cn/")
> > 
> > driver.find_element_by_xpath('//a[@class="normal-login-tab"]').click()  # 切换登录方式
> > 
> > driver.find_element_by_xpath('//input[@id="vwriter"]').send_keys(username)  # 输入用户
> > driver.find_element_by_xpath('//input[@type="password"]').send_keys(password)  # 输入密码
> > driver.find_element_by_xpath("//button[@class='loginWin-submit-btn']").click()  # 点击登录
> > 
> > # todo 需要在这里判断是否登录成功
> > print(driver.page_source)
> > driver.close()
> > ```
> > if **name** == '**main**':
> > # 在这里输入用户名，密码
> > get_cookies(username="", password="")
> 
> 感谢，想用http请求去模拟登录

so, 你需要action算法

**Comment by fengyelingdu** [comment]
> 
> 
> > > from selenium import webdriver
> > > def get_cookies(username, password):
> > > ```
> > > driver = webdriver.Chrome()
> > > 
> > > driver.get("http://www.tianya.cn/")
> > > 
> > > driver.find_element_by_xpath('//a[@class="normal-login-tab"]').click()  # 切换登录方式
> > > 
> > > driver.find_element_by_xpath('//input[@id="vwriter"]').send_keys(username)  # 输入用户
> > > driver.find_element_by_xpath('//input[@type="password"]').send_keys(password)  # 输入密码
> > > driver.find_element_by_xpath("//button[@class='loginWin-submit-btn']").click()  # 点击登录
> > > 
> > > # todo 需要在这里判断是否登录成功
> > > print(driver.page_source)
> > > driver.close()
> > > ```
> > > if **name** == '**main**':
> > > # 在这里输入用户名，密码
> > > get_cookies(username="", password="")
> > 
> > 
> > 感谢，想用http请求去模拟登录
> 
> so, 你需要action算法

[js中有action算法，就是不太懂[](url)]([url](url))

> 
> 
> > > from selenium import webdriver
> > > def get_cookies(username, password):
> > > ```
> > > driver = webdriver.Chrome()
> > > 
> > > driver.get("http://www.tianya.cn/")
> > > 
> > > driver.find_element_by_xpath('//a[@class="normal-login-tab"]').click()  # 切换登录方式
> > > 
> > > driver.find_element_by_xpath('//input[@id="vwriter"]').send_keys(username)  # 输入用户
> > > driver.find_element_by_xpath('//input[@type="password"]').send_keys(password)  # 输入密码
> > > driver.find_element_by_xpath("//button[@class='loginWin-submit-btn']").click()  # 点击登录
> > > 
> > > # todo 需要在这里判断是否登录成功
> > > print(driver.page_source)
> > > driver.close()
> > > ```
> > > if **name** == '**main**':
> > > # 在这里输入用户名，密码
> > > get_cookies(username="", password="")
> > 
> > 
> > 感谢，想用http请求去模拟登录
> 
> so, 你需要action算法

看了下有个js文件是专门生成action的，就是不太懂
